#!/bin/bash

NODE_NAME=$1

echo "Initializing certificates for node: $NODE_NAME"

# Wait for certificates to be generated by nifi-toolkit
echo "Waiting for certificates to be generated..."
while [ ! -f "/opt/certs/$NODE_NAME/keystore.jks" ] || [ ! -f "/opt/certs/$NODE_NAME/truststore.jks" ]; do
    echo "Waiting for certificates..."
    sleep 5
done

echo "Certificates found. Copying to NiFi conf directory..."

# Copy certificates to NiFi conf directory
cp "/opt/certs/$NODE_NAME/keystore.jks" "/opt/nifi/nifi-current/conf/"
cp "/opt/certs/$NODE_NAME/truststore.jks" "/opt/nifi/nifi-current/conf/"

# Copy nifi.properties if it exists
if [ -f "/opt/certs/$NODE_NAME/nifi.properties" ]; then
    echo "Copying nifi.properties for $NODE_NAME"
    cp "/opt/certs/$NODE_NAME/nifi.properties" "/opt/nifi/nifi-current/conf/"
else
    echo "No nifi.properties found for $NODE_NAME, using default configuration"
fi

echo "Certificate initialization complete for $NODE_NAME"

# Start NiFi
exec /opt/nifi/scripts/start.sh
